### ISSUE TITLE
Kinematic solution from that paper is too restrictive

### ISSUE THREAD

**Issue by garamizo** [hirolab/gait-emulator#1]
The paper assumes the robot has a base and top plate in a triangular shape, with equal lengths. This is too restrictive.

I added a solution to the general case.
It should be correct. But please check that.
See https://github.com/hirolab/gait-emulator/tree/master/planar_parallel_manipulator

If it is correct and you know how to use it, please close the issue.

**Comment by solimana** [comment]
Thanks a lot ! I figured how to use it and i am currently extracting d1,d2,d3 variables and attaching them to multi-body model.
